### ISSUE TITLE
Discord notification Error

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/starrail-auto#30]
After using the new Discord.js code, I encountered the following error

2023-12-28 11:11:00 RequestError: Response code 400 (Bad Request)
2023-12-28 11:11:00 - args: {"statusCode":400,"statusMessage":"Bad Request","hostname":"discord.com"}
2023-12-28 11:11:00     at Request._destroy (file:///usr/src/app/node_modules/got/dist/source/core/index.js:482:21)
2023-12-28 11:11:00     at _destroy (node:internal/streams/destroy:109:10)
2023-12-28 11:11:00     at Request.destroy (node:internal/streams/destroy:71:5)
2023-12-28 11:11:00     at Request._error (file:///usr/src/app/node_modules/got/dist/source/core/index.js:1012:14)
2023-12-28 11:11:00     at gotModule.extend.hooks.beforeError (file:///usr/src/app/lib/got.js:18:11)
2023-12-28 11:11:00     at Request._error (file:///usr/src/app/node_modules/got/dist/source/core/index.js:1005:35)
2023-12-28 11:11:00     at file:///usr/src/app/node_modules/got/dist/source/core/index.js:402:23
2023-12-28 11:11:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2023-12-28 11:11:00   input: undefined,
2023-12-28 11:11:00   code: 'ERR_GOT_REQUEST_ERROR',

I can run the bot without issues using the old code, but after switching to the new Discord.js code, I encounter errors. I'm having trouble pinpointing the issue. Can you help me? I'm launching it using Docker

**Comment by Capoouo** [comment]
The complete error code is here

2023-12-28 11:11:00 RequestError: Response code 400 (Bad Request)
2023-12-28 11:11:00 - args: {"statusCode":400,"statusMessage":"Bad Request","hostname":"discord.com"}
2023-12-28 11:11:00     at Request._destroy (file:///usr/src/app/node_modules/got/dist/source/core/index.js:482:21)
2023-12-28 11:11:00     at _destroy (node:internal/streams/destroy:109:10)
2023-12-28 11:11:00     at Request.destroy (node:internal/streams/destroy:71:5)
2023-12-28 11:11:00     at Request._error (file:///usr/src/app/node_modules/got/dist/source/core/index.js:1012:14)
2023-12-28 11:11:00     at gotModule.extend.hooks.beforeError (file:///usr/src/app/lib/got.js:18:11)
2023-12-28 11:11:00     at Request._error (file:///usr/src/app/node_modules/got/dist/source/core/index.js:1005:35)
2023-12-28 11:11:00     at file:///usr/src/app/node_modules/got/dist/source/core/index.js:402:23
2023-12-28 11:11:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2023-12-28 11:11:00   input: undefined,
2023-12-28 11:11:00   code: 'ERR_GOT_REQUEST_ERROR',
2023-12-28 11:11:00   timings: {
2023-12-28 11:11:00     start: 1703733060412,
2023-12-28 11:11:00     socket: 1703733060412,
2023-12-28 11:11:00     lookup: 1703733060416,
2023-12-28 11:11:00     connect: 1703733060422,
2023-12-28 11:11:00     secureConnect: 1703733060428,
2023-12-28 11:11:00     upload: 1703733060428,
2023-12-28 11:11:00     response: 1703733060734,
2023-12-28 11:11:00     end: 1703733060735,
2023-12-28 11:11:00     error: undefined,
2023-12-28 11:11:00     abort: undefined,
2023-12-28 11:11:00     phases: {
2023-12-28 11:11:00       wait: 0,
2023-12-28 11:11:00       dns: 4,
2023-12-28 11:11:00       tcp: 6,
2023-12-28 11:11:00       tls: 6,
2023-12-28 11:11:00       request: 0,
2023-12-28 11:11:00       firstByte: 306,
2023-12-28 11:11:00       download: 1,
2023-12-28 11:11:00       total: 323
2023-12-28 11:11:00     }
2023-12-28 11:11:00   },
2023-12-28 11:11:00   options: {
2023-12-28 11:11:00     request: undefined,
2023-12-28 11:11:00     agent: { http: undefined, https: undefined, http2: undefined },
2023-12-28 11:11:00     h2session: undefined,
2023-12-28 11:11:00     decompress: true,
2023-12-28 11:11:00     timeout: {
2023-12-28 11:11:00       connect: undefined,
2023-12-28 11:11:00       lookup: undefined,
2023-12-28 11:11:00       read: undefined,
2023-12-28 11:11:00       request: 30000,
2023-12-28 11:11:00       response: undefined,
2023-12-28 11:11:00       secureConnect: undefined,
2023-12-28 11:11:00       send: undefined,
2023-12-28 11:11:00       socket: undefined
2023-12-28 11:11:00     },
2023-12-28 11:11:00     prefixUrl: '',
2023-12-28 11:11:00     body: '{"embeds":[{}],"username":"Honkai: Star Rail","avatar_url":"https://i.imgur.com/o0hyhmw.png"}',
2023-12-28 11:11:00     form: undefined,
2023-12-28 11:11:00     json: undefined,
2023-12-28 11:11:00     cookieJar: undefined,
2023-12-28 11:11:00     ignoreInvalidCookies: false,
2023-12-28 11:11:00     searchParams: undefined,
2023-12-28 11:11:00     dnsLookup: undefined,
2023-12-28 11:11:00     dnsCache: undefined,
2023-12-28 11:11:00     context: {},
2023-12-28 11:11:00     hooks: {
2023-12-28 11:11:00       init: [],
2023-12-28 11:11:00       beforeRequest: [],
2023-12-28 11:11:00       beforeError: [ [Function (anonymous)] ],
2023-12-28 11:11:00       beforeRedirect: [],
2023-12-28 11:11:00       beforeRetry: [],
2023-12-28 11:11:00       afterResponse: []
2023-12-28 11:11:00     },
2023-12-28 11:11:00     followRedirect: true,
2023-12-28 11:11:00     maxRedirects: 10,
2023-12-28 11:11:00     cache: undefined,
2023-12-28 11:11:00     throwHttpErrors: true,
2023-12-28 11:11:00     username: '',
2023-12-28 11:11:00     password: '',
2023-12-28 11:11:00     http2: false,
2023-12-28 11:11:00     allowGetBody: false,
2023-12-28 11:11:00     headers: {
2023-12-28 11:11:00       'user-agent': 'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Mobile Safari/537.36',
2023-12-28 11:11:00       'content-type': 'application/json',
2023-12-28 11:11:00       'content-length': '93',
2023-12-28 11:11:00       accept: 'application/json',
2023-12-28 11:11:00       'accept-encoding': 'gzip, deflate, br'
2023-12-28 11:11:00     },
2023-12-28 11:11:00     methodRewriting: false,
2023-12-28 11:11:00     dnsLookupIpVersion: undefined,
2023-12-28 11:11:00     parseJson: [Function: parse],
2023-12-28 11:11:00     stringifyJson: [Function: stringify],
2023-12-28 11:11:00     retry: {
2023-12-28 11:11:00       limit: 0,
2023-12-28 11:11:00       methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
2023-12-28 11:11:00       statusCodes: [
2023-12-28 11:11:00         408, 413, 429, 500,
2023-12-28 11:11:00         502, 503, 504, 521,
2023-12-28 11:11:00         522, 524
2023-12-28 11:11:00       ],
2023-12-28 11:11:00       errorCodes: [
2023-12-28 11:11:00         'ETIMEDOUT',
2023-12-28 11:11:00         'ECONNRESET',
2023-12-28 11:11:00         'EADDRINUSE',
2023-12-28 11:11:00         'ECONNREFUSED',
2023-12-28 11:11:00         'EPIPE',
2023-12-28 11:11:00         'ENOTFOUND',
2023-12-28 11:11:00         'ENETUNREACH',
2023-12-28 11:11:00         'EAI_AGAIN'
2023-12-28 11:11:00       ],
2023-12-28 11:11:00       maxRetryAfter: undefined,
2023-12-28 11:11:00       calculateDelay: [Function: calculateDelay],
2023-12-28 11:11:00       backoffLimit: Infinity,
2023-12-28 11:11:00       noise: 100
2023-12-28 11:11:00     },
2023-12-28 11:11:00     localAddress: undefined,
2023-12-28 11:11:00     method: 'POST',
2023-12-28 11:11:00     createConnection: undefined,
2023-12-28 11:11:00     cacheOptions: {
2023-12-28 11:11:00       shared: undefined,
2023-12-28 11:11:00       cacheHeuristic: undefined,
2023-12-28 11:11:00       immutableMinTimeToLive: undefined,
2023-12-28 11:11:00       ignoreCargoCult: undefined
2023-12-28 11:11:00     },
2023-12-28 11:11:00     https: {
2023-12-28 11:11:00       alpnProtocols: undefined,
2023-12-28 11:11:00       rejectUnauthorized: undefined,
2023-12-28 11:11:00       checkServerIdentity: undefined,
2023-12-28 11:11:00       certificateAuthority: undefined,
2023-12-28 11:11:00       key: undefined,
2023-12-28 11:11:00       certificate: undefined,
2023-12-28 11:11:00       passphrase: undefined,
2023-12-28 11:11:00       pfx: undefined,
2023-12-28 11:11:00       ciphers: undefined,
2023-12-28 11:11:00       honorCipherOrder: undefined,
2023-12-28 11:11:00       minVersion: undefined,
2023-12-28 11:11:00       maxVersion: undefined,
2023-12-28 11:11:00       signatureAlgorithms: undefined,
2023-12-28 11:11:00       tlsSessionLifetime: undefined,
2023-12-28 11:11:00       dhparam: undefined,
2023-12-28 11:11:00       ecdhCurve: undefined,
2023-12-28 11:11:00       certificateRevocationLists: undefined
2023-12-28 11:11:00     },
2023-12-28 11:11:00     encoding: undefined,
2023-12-28 11:11:00     resolveBodyOnly: false,
2023-12-28 11:11:00     isStream: false,
2023-12-28 11:11:00     responseType: 'json',
2023-12-28 11:11:00     url: URL {
2023-12-28 11:11:00       href: 'https://discord.com/api/webhooks/1189764287061823598/CReJoXXXXXXXXXXXXXXXXXXXXXXXXXWfNGJxCBos0PXM5hnz',
2023-12-28 11:11:00       origin: 'https://discord.com',
2023-12-28 11:11:00       protocol: 'https:',
2023-12-28 11:11:00       username: '',
2023-12-28 11:11:00       password: '',
2023-12-28 11:11:00       host: 'discord.com',
2023-12-28 11:11:00       hostname: 'discord.com',
2023-12-28 11:11:00       port: '',
2023-12-28 11:11:00       pathname: '/api/webhooks/1189764287061823598/CReJXXXXXXXXXXXXXXXXXXXXXXXXXXXM5hnz',
2023-12-28 11:11:00       search: '',
2023-12-28 11:11:00       searchParams: URLSearchParams {},
2023-12-28 11:11:00       hash: ''
2023-12-28 11:11:00     },
2023-12-28 11:11:00     pagination: {
2023-12-28 11:11:00       transform: [Function: transform],
2023-12-28 11:11:00       paginate: [Function: paginate],
2023-12-28 11:11:00       filter: [Function: filter],
2023-12-28 11:11:00       shouldContinue: [Function: shouldContinue],
2023-12-28 11:11:00       countLimit: Infinity,
2023-12-28 11:11:00       backoff: 0,
2023-12-28 11:11:00       requestLimit: 10000,
2023-12-28 11:11:00       stackAllItems: false
2023-12-28 11:11:00     },
2023-12-28 11:11:00     setHost: true,
2023-12-28 11:11:00     maxHeaderSize: undefined,
2023-12-28 11:11:00     signal: undefined,
2023-12-28 11:11:00     enableUnixSockets: true
2023-12-28 11:11:00   }
2023-12-28 11:11:00 }

I have re-cloned and run docker again, but I still encounter the same error code. I'm not sure where the issue is

----------------------------------------------------------------------------------------------------------------------------

Later, I also tested it on my local machine, and I encountered the same error

**Comment by torikushiii** [comment]
Thank you for reporting this bug, I've fixed this error on the latest commit

**Comment by Capoouo** [comment]
It's working . Thank you.

**Comment by Capoouo** [comment]
I have a question. If I delete 'crons/check-code-redeem/codes.js,' will I still receive notifications on Discord for newly generated codes after 30 minutes? It seems that it's not working properly if it does notify.

**Comment by Capoouo** [comment]
I think I've grasped how it operates. Thank you for continuously updating this project! I really appreciate it.
